// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEjy0XIHBVFblUjyJtiBk04f1N2uw3mgc',
    appId: '1:1012556906053:web:e7b9d8f3b3ef07d19ced2c',
    messagingSenderId: '1012556906053',
    projectId: 'interview-fbd3a',
    authDomain: 'interview-fbd3a.firebaseapp.com',
    databaseURL: 'https://interview-fbd3a-default-rtdb.firebaseio.com',
    storageBucket: 'interview-fbd3a.appspot.com',
    measurementId: 'G-J0HD04NEXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr1vStAYOIEKh2vFt4AHZ28ci24_vzh74',
    appId: '1:1012556906053:android:a595150c0bfb586c9ced2c',
    messagingSenderId: '1012556906053',
    projectId: 'interview-fbd3a',
    databaseURL: 'https://interview-fbd3a-default-rtdb.firebaseio.com',
    storageBucket: 'interview-fbd3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJdcnALa9Dwo1z_4nxvCi7PTCb0GFs95o',
    appId: '1:1012556906053:ios:d7638c642c7f1d9c9ced2c',
    messagingSenderId: '1012556906053',
    projectId: 'interview-fbd3a',
    databaseURL: 'https://interview-fbd3a-default-rtdb.firebaseio.com',
    storageBucket: 'interview-fbd3a.appspot.com',
    iosBundleId: 'com.example.flutterInterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJdcnALa9Dwo1z_4nxvCi7PTCb0GFs95o',
    appId: '1:1012556906053:ios:3f5bace85498ee989ced2c',
    messagingSenderId: '1012556906053',
    projectId: 'interview-fbd3a',
    databaseURL: 'https://interview-fbd3a-default-rtdb.firebaseio.com',
    storageBucket: 'interview-fbd3a.appspot.com',
    iosBundleId: 'com.example.flutterInterview.RunnerTests',
  );
}
